# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelBuddies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravelBuddies
  pod 'Parse'

  target 'TravelBuddiesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravelBuddiesUITests' do
    # Pods for testing
  end

end
